/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package altraductor;

/**
 * @author betio_000
 */
public enum Token {
    suma, multiplicacion, division, resta, NUMERO, ERROR, ART_INDEF, ART_DEFI, 
    SUS_ABSTRACT, SUS_COMUN, SUS_PROPIO, ADJ_POSESIV,ADJ_DEMOS,ADJ_CALIFI,ADJ_NUMCARDIN,ADJ_NUMORD,
    ADJ_PROPERSO,ADJ_PROPOSESIV,ADJ_PROREFLEX,ADJ_PROINTERR,PREP_MOD,PREP_LUG,PREP_MOV,PREP_TIEM
   ,SIG_PUNT,VERBO_PRESENT,VERBO_PASADOSIMP,VERBO_PASADOPARTICI,CONJ_COORADVERV,CONJ_COORCOPU,CONJ_COORDISYU,
   CONJ_SUBORDISYU,CONJ_SUBORCAUS,CONJ_CONJSUBOCONSEC,CONJ_CONJSUBOCONCES,CONJ_CONJSUBOCOMPARA,
   AUX_PAS, AUX_PRESEN, WEATH, PROF, ADV_TIME,ADV_FRECUENCIA,ADV_LUG,ADV_MANERA,VEGET,PAIS,ANIMALS;
}
